{% set name = "gradle-language-server" %}
{% set version = "3.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/vscode-gradle/archive/{{ version }}.tar.gz
  sha256: 876c06980376d136680f0254e01d1508be016552a024ad76457f03e899062317

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - nodejs
    - openjdk =11
  run:
    - openjdk

test:
  commands:
    - gradle-language-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/microsoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE.md
    - build/reports/dependency-license/
  summary: Manage Gradle Projects, run Gradle tasks and provide better Gradle file authoring experience
  dev_url: https://github.com/microsoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
