{% set name = "gradle-language-server" %}
{% set version = "3.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/vscode-gradle/archive/{{ version }}.tar.gz
  sha256: 5c8874e7959242821c81e70ea11a8eb6ece1d466190c4dd4d37b07325a381d7c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - nodejs
    - openjdk =17
  run:
    - openjdk

test:
  commands:
    - gradle-language-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/microsoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE.md
    - build/reports/dependency-license/
  summary: Manage Gradle Projects, run Gradle tasks and provide better Gradle file authoring experience
  dev_url: https://github.com/microsoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
