{% set name = "gradle-language-server" %}
{% set version = "3.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/vscode-gradle/archive/{{ version }}.tar.gz
  sha256: c2afb03744dc273625056626b100f8a7881d7edfb9b16df65832c8580590463a

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - nodejs
    - openjdk =11
  run:
    - openjdk

test:
  commands:
    - gradle-language-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/microsoft/{{ name }}
  license: MIT
  license_file:
    - LICENSE.md
    - build/reports/dependency-license/
  summary: Manage Gradle Projects, run Gradle tasks and provide better Gradle file authoring experience
  dev_url: https://github.com/microsoft/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
